apiVersion: apps/v1
kind: Deployment
metadata:
  name:  springbootdocker
  labels:
    type: backend
    app: springbootdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: springbootdocker
  template:
    metadata:
      name: springbootdocker
      labels:
        type: backend
        app: springbootdocker
    spec:
      containers:
        - name: nodecontainer
          image: gcr.io/gcp-dev-426803/gcp-springboot-applications
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: springboot-load-service
spec:
  ports:
    - port: 80 
      targetPort: 8080
  selector:
    type: backend
    app: springbootdocker  
  type: LoadBalancer
